namespace PlantonHub.Application.DTOs.Biometric;

/// <summary>
/// Request to enroll a face embedding for a user.
/// The embedding is generated client-side (Flutter app) using FaceNet/MobileFaceNet.
/// </summary>
public class FaceEnrollmentRequest
{
    /// <summary>
    /// 128-dimensional facial embedding vector generated by the mobile app.
    /// </summary>
    public float[] Embedding { get; set; } = Array.Empty<float>();

    /// <summary>
    /// Optional: base64-encoded enrollment photo for admin review/audit.
    /// </summary>
    public string? PhotoBase64 { get; set; }
}
