namespace PlantonHub.Domain.Entities;

/// <summary>
/// Stores a facial embedding for biometric identity verification.
/// Each user can have multiple enrollments (different angles/lighting).
/// The embedding is a 128-dimensional float vector generated by FaceNet/MobileFaceNet
/// on the client device (Flutter app) and sent to the backend for storage.
/// </summary>
public class FaceEnrollment
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }

    /// <summary>
    /// 128-dimensional facial embedding vector (FaceNet standard).
    /// Stored as a float array in PostgreSQL (real[] column).
    /// </summary>
    public float[] Embedding { get; set; } = Array.Empty<float>();

    /// <summary>
    /// Optional: URL or path to the enrollment photo (for admin review/audit).
    /// </summary>
    public string? PhotoUrl { get; set; }

    public bool IsActive { get; set; } = true;
    public DateTime CreatedAt { get; set; }

    // Navigation
    public User User { get; set; } = null!;
}
