// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantonHub.Infrastructure.Data;

#nullable disable

namespace PlantonHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717051616_DropRefreshTokens")]
    partial class DropRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantonHub.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryActionLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("RelatedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecondaryActionLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("IX_Alert_ClinicId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Alert_Code");

                    b.HasIndex("RelatedUserId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("IsResolved", "CreatedAt")
                        .HasDatabaseName("IX_Alert_IsResolved_CreatedAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BiometricValidated")
                        .HasColumnType("boolean");

                    b.Property<string>("CheckInDeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("CheckInLatitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CheckInLocalDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("CheckInLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CheckInServerDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CheckOutDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("CheckOutLatitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CheckOutLocalDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("CheckOutLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CheckOutServerDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocalEventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<int>("SyncSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("SyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AfterValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("BeforeValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Module")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Module")
                        .HasDatabaseName("IX_AuditLog_Module");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLog_Timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLog_UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.AvailabilityRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BlockedShiftsMask")
                        .HasColumnType("integer");

                    b.Property<int?>("BlockedWeekdaysMask")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AvailabilityRestriction_UserId");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_AvailabilityRestriction_DateRange");

                    b.ToTable("AvailabilityRestrictions");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("AllowedRadiusMeters")
                        .HasColumnType("double precision");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int?>("CheckInToleranceMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DoctorsPerShift")
                        .HasColumnType("integer");

                    b.Property<bool>("HasNursing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.ClinicShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfessionalType")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredStaff")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicShiftTemplates");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MinSlaPercent")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MonthlyValue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PublicOrganId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicOrganId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.DeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_DeviceRegistration_UserId_IsActive");

                    b.ToTable("DeviceRegistrations");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.DeviceUnlinkAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OldDeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UnlinkedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UnlinkedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_DeviceUnlinkAudit_UserId");

                    b.ToTable("DeviceUnlinkAudits");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.FaceEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_FaceEnrollment_UserId_IsActive");

                    b.ToTable("FaceEnrollments");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Justification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbsentUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("RespondedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ShiftTurn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbsentUserId");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("IX_Justification_ClinicId");

                    b.HasIndex("ProtocolNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Justification_ProtocolNumber");

                    b.HasIndex("RespondedByUserId");

                    b.HasIndex("ShiftDate")
                        .HasDatabaseName("IX_Justification_ShiftDate");

                    b.ToTable("Justifications");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.OfflineAttendanceEvent", b =>
                {
                    b.Property<Guid>("OfflineAttendanceEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AntiFraudFlags")
                        .HasColumnType("text");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AttendanceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("BiometricValidated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LocalDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LocalEventId")
                        .HasColumnType("uuid");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReceivedAtServer")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationMessages")
                        .HasColumnType("text");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer");

                    b.HasKey("OfflineAttendanceEventId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.HasIndex("LocalEventId", "UserId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("IX_OfflineAttendanceEvent_Idempotency");

                    b.ToTable("OfflineAttendanceEvents");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.OfflineSyncAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LocalDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LocalEventId")
                        .HasColumnType("uuid");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReceivedAtServer")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RejectionOrReviewReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ValidationResult")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("IX_OfflineSyncAuditLog_ClinicId");

                    b.HasIndex("LocalEventId")
                        .HasDatabaseName("IX_OfflineSyncAuditLog_LocalEventId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_OfflineSyncAuditLog_UserId");

                    b.ToTable("OfflineSyncAuditLogs");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.PublicOrgan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acronym")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("PublicOrgans");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.ShiftAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ShiftId", "UserId")
                        .IsUnique();

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Substitution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbsentUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ReasonType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("ShiftEndTime")
                        .HasColumnType("interval");

                    b.Property<string>("ShiftLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("ShiftStartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubstituteUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AbsentUserId");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("IX_Substitution_ClinicId");

                    b.HasIndex("ShiftDate")
                        .HasDatabaseName("IX_Substitution_ShiftDate");

                    b.HasIndex("SubstituteUserId");

                    b.ToTable("Substitutions");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AbsenceThresholdMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("AzureEndpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AzureRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BiometricAllowManualCheckin")
                        .HasColumnType("boolean");

                    b.Property<int>("BiometricConfidencePercent")
                        .HasColumnType("integer");

                    b.Property<bool>("BiometricLogFailedAttempt")
                        .HasColumnType("boolean");

                    b.Property<int>("BiometricMaxAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("CheckInBlockAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("CheckInToleranceMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("DaylightSavingAuto")
                        .HasColumnType("boolean");

                    b.Property<bool>("DetailedAuditLog")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailCc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MfaRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("NotificationChannelsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotifyOnAbsence")
                        .HasColumnType("boolean");

                    b.Property<string>("OrgCnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PasswordRotationDays")
                        .HasColumnType("integer");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SystemTimezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int?>("ProfessionalType")
                        .HasColumnType("integer");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.UserClinicRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("UserId", "ClinicId", "Role")
                        .IsUnique();

                    b.ToTable("UserClinicRoles");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Alert", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlantonHub.Domain.Entities.User", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlantonHub.Domain.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinic");

                    b.Navigation("RelatedUser");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.Clinic", "Clinic")
                        .WithMany("Attendances")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.Shift", "Shift")
                        .WithMany("Attendances")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.AvailabilityRestriction", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Clinic", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.Contract", "Contract")
                        .WithMany("Clinics")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.ClinicShiftTemplate", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.Clinic", "Clinic")
                        .WithMany("ShiftTemplates")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Contract", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.PublicOrgan", "PublicOrgan")
                        .WithMany("Contracts")
                        .HasForeignKey("PublicOrganId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PublicOrgan");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.DeviceRegistration", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany("DeviceRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.DeviceUnlinkAudit", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany("DeviceUnlinkAudits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.FaceEnrollment", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany("FaceEnrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Justification", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.User", "AbsentUser")
                        .WithMany()
                        .HasForeignKey("AbsentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.User", "RespondedByUser")
                        .WithMany()
                        .HasForeignKey("RespondedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AbsentUser");

                    b.Navigation("Clinic");

                    b.Navigation("RespondedByUser");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.OfflineAttendanceEvent", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.OfflineSyncAuditLog", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.PublicOrgan", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.PublicOrgan", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Shift", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.Clinic", "Clinic")
                        .WithMany("Shifts")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.Shift", "Shift")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Substitution", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.User", "AbsentUser")
                        .WithMany()
                        .HasForeignKey("AbsentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.User", "SubstituteUser")
                        .WithMany()
                        .HasForeignKey("SubstituteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AbsentUser");

                    b.Navigation("Clinic");

                    b.Navigation("SubstituteUser");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.UserClinicRole", b =>
                {
                    b.HasOne("PlantonHub.Domain.Entities.Clinic", "Clinic")
                        .WithMany("UserClinicRoles")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantonHub.Domain.Entities.User", "User")
                        .WithMany("UserClinicRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Clinic", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ShiftTemplates");

                    b.Navigation("Shifts");

                    b.Navigation("UserClinicRoles");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.PublicOrgan", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.Shift", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("PlantonHub.Domain.Entities.User", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("AuditLogs");

                    b.Navigation("DeviceRegistrations");

                    b.Navigation("DeviceUnlinkAudits");

                    b.Navigation("FaceEnrollments");

                    b.Navigation("ShiftAssignments");

                    b.Navigation("UserClinicRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
